### PR TITLE
Optional node.fixedValue to override size of node

### PR DESCRIPTION
**Pull request by sillitoe**
We have a use case where it is useful to allow the size of each node to be larger than the sum of the _link_.value (overriding the default case).

e.g.

image

I can't figure out a clean way of implementing this in the current API, so I've added a local workaround that allows an optional _node_.value to be added to the existing `Math.max` calculation. 

Is this (or a better implementation) something that might be useful to others?

Thanks,

Ian

### CODE REVIEW

**Comment by elliotchi** [comment]
+1 on this. Can we get this merged?

**Comment by dandelany** [comment]
+1, this would be really valuable for my use-case as well! Would be great if this were supported.

**Comment by craigmcginley** [comment]
+1

**Comment by bvoisin** [comment]
+1, can we help to get it merged ?

**Comment by geekplux** [comment]
+1, this would be really useful

**Comment by sillitoe** [comment]
@mbostock ?

**Comment by mbostock** [comment]
The issue I see with this design is that you can’t run the Sankey layout again on the same input: the *node*.value set by the previous run of the Sankey layout becomes the new minimum value of the node. So, this is not strictly backwards-compatible.

We tackled a similar issue in https://github.com/d3/d3-hierarchy/issues/9 by wrapping the input data, so that the layout isn’t overwriting the same value it reads from. I think we’ll probably want to do that with the Sankey input, too—to treat the input data as immutable, and to wrap it with whatever the layout generates.

A super-simple way of avoiding this problem would be to read from *node*.minValue instead.

**Comment by sillitoe** [comment]
Thanks, yes that seems a much better design - added in c03678f.

**Comment by mbostock** [comment]
Thanks. Would it be better specify a *node*.fixedValue, rather than a *node*.minValue? Then you would say:

```js
node.value = node.fixedValue === undefined
    ? Math.max(sum(node.sourceLinks, value), sum(node.targetLinks, value))
    : node.fixedValue;
```

**Comment by sillitoe** [comment]
I figured this might cause a rendering problem if the nodes were smaller than the incoming links?

**Comment by mbostock** [comment]
Yep, but isn’t that more of a data problem than a rendering problem? It seems better to do that than to ignore the input value.

**Comment by sillitoe** [comment]
Yes, makes sense. Looks good to me.

**Comment by vdubr** [comment]
Hi, what is the state of this pull request? This function would be very useful for us. Can I help?

**Comment by vdubr** [comment]
Thanks

**Pull request merged**
