### PR TITLE
Re-enable energy unit test

### PR DESCRIPTION
**Pull request by jayaddison**
Re-enables the skipped 'energy' sankey test; this requires updating some of the test expectations.

### CODE REVIEW

**Comment by jayaddison** [comment]
Does this look reasonable @curran @Fil @mbostock?

I'd like to merge this (and #87) before adding test coverage to #71.

(apologies for the multi-ping; if there's a better way to ping for d3 reviews, and/or if I should just wait in future, please let me know :))

**Comment by Fil** [comment]
Well I've never contributed to this repo (and never used it), so I have to pass :)
But adding or fixing a test is (almost) always a good idea.

**Comment by jayaddison** [comment]
No probs, thanks :)

**Comment by jayaddison** [comment]
Ping @mbostock; this pull request re-enables a unit test for `d3-sankey`.

**Comment by jayaddison** [comment]
Just checking in again to see whether we could re-enable this unit test; this would unblock continued progress on #71.

**Review by curran — APPROVED** [review]
LGTM

**Comment by jayaddison** [comment]
ping @mbostock (after merging this and #87, I plan to add test coverage to #71, per review feedback there)

**Comment by jayaddison** [comment]
@mbostock any chance of review on this change to re-enable a unit test (with updated test expectations)?  I'd like to do that before adding test coverage in #71 (vertical sankey orientation support).

**Pull request closed without merging**
